version: '3.3'

services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    networks:
      - app_net
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    networks:
      - app_net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PWD}
    ports:
      - "27017:27017"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks:
      - app_net
    ports:
      - 8080:8080
    depends_on:
      - db

networks:
  app_net:
    driver: bridge
